/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.0.0.24.1
    Soft IP Version: 1.0.2
    2024 01 17 10:40:47
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module brom8k (rd_clk_i, rst_i, rd_en_i, rd_clk_en_i, rd_addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rd_clk_i;
    input  rst_i;
    input  rd_en_i;
    input  rd_clk_en_i;
    input  [12:0]  rd_addr_i;
    output  [7:0]  rd_data_o;
endmodule